CREATE TABLE `USER` (
	`USER_ID`	VARCHAR(50)	NOT NULL,
	`USER_NAME`	VARCHAR(255)	NULL
);

CREATE TABLE `CHOICE` (
	`CHOICE_ID`	VARCHAR(50)	NOT NULL,
	`QUESTION_ID`	VARCHAR(50)	NOT NULL,
	`CHOICE_CHOICE`	VARCHAR(255)	NULL,
	`CHOICE_CORRECT`	VARCHAR(255)	NULL,
	`CHOICE_NUM`	INTEGER	NULL
);


CREATE TABLE `RESULT` (
	`RESULT_ID`	VARCHAR(50)	NOT NULL,
	`USER_ID`	VARCHAR(50)	NOT NULL,
	`QUESTION_ID`	VARCHAR(50)	NOT NULL,
	`CHOICE_ID`	VARCHAR(50)	NOT NULL
);

CREATE TABLE `QUESTION` (
	`QUESTION_ID`	VARCHAR(50)	NOT NULL,
	`QUESTION_TITLE`	VARCHAR(255)	NULL,
	`QUESTION_SCORE`	INTEGER	NULL
);

ALTER TABLE `USER` ADD CONSTRAINT `PK_USER` PRIMARY KEY (
	`USER_ID`
);

ALTER TABLE `CHOICE` ADD CONSTRAINT `PK_CHOICE` PRIMARY KEY (
	`CHOICE_ID`,
	`QUESTION_ID`
);

ALTER TABLE `RESULT` ADD CONSTRAINT `PK_RESULT` PRIMARY KEY (
	`RESULT_ID`,
	`USER_ID`,
	`QUESTION_ID`,
	`CHOICE_ID`
);

ALTER TABLE `QUESTION` ADD CONSTRAINT `PK_QUESTION` PRIMARY KEY (
	`QUESTION_ID`
);

ALTER TABLE `CHOICE` ADD CONSTRAINT `FK_QUESTION_TO_CHOICE_1` FOREIGN KEY (
	`QUESTION_ID`
)
REFERENCES `QUESTION` (
	`QUESTION_ID`
);

ALTER TABLE `RESULT` ADD CONSTRAINT `FK_USER_TO_RESULT_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USER` (
	`USER_ID`
);

ALTER TABLE `RESULT` ADD CONSTRAINT `FK_QUESTION_TO_RESULT_1` FOREIGN KEY (
	`QUESTION_ID`
)
REFERENCES `QUESTION` (
	`QUESTION_ID`
);

ALTER TABLE `RESULT` ADD CONSTRAINT `FK_CHOICE_TO_RESULT_1` FOREIGN KEY (
	`CHOICE_ID`
)
REFERENCES `CHOICE` (
	`CHOICE_ID`
);


